## Needs clusters labeled "env: dev"
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: guestbook
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-sync-succeeded.slack: argo
spec:
  generators:
  - clusters:
      selector:
        matchLabels:
          env: dev
  syncPolicy:
    preserveResourcesOnDeletion: true
  template: 
    metadata:
      name: '{{name}}-guestbook'
      labels:
        applicationset: argo-app-test-dev
        cluster: '{{name}}'
        env: dev
    spec:
      project: "default"
      source:
        repoURL: https://github.com/argoproj/argocd-example-apps/
        targetRevision: HEAD
        path: guestbook
      destination:
        server: '{{server}}'
        namespace: guestbook
      syncPolicy:
        automated:
          prune: false
          selfHeal: false
        syncOptions:
        - CreateNamespace=true